services:
  - type: web
    name: voila-whatif
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila Graph.ipynb --port=$PORT --no-browser --Voila.configuration.allow_origin="*"
    plan: free
    autoDeploy: true
