services:
  - type: web
    name: whatif
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila whatif.ipynb --port=$PORT --no-browser --Voila.ip=0.0.0.0 --Voila.tornado_settings='{"headers": {"Access-Control-Allow-Origin": "*"}}' --Voila.server.enable_nbextensions=True
