services:
  - type: web
    name: whatif-voila
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila whatif.ipynb --port=$PORT --no-browser --ip=0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: VOILA_APP
        value: whatif.ipynb
