services:
  - type: web
    name: voila-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: voila whatif.ipynb --port=$PORT --no-browser --ip=0.0.0.0
