services:
  - type: web
    name: whatif-voila
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila whatif.ipynb --port=$PORT --no-browser
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
