services:
  - type: web
    name: whatif
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: voila whatif.ipynb --port=$PORT --host=0.0.0.0 --no-browser --Voila.server.allow_origin="*" --Voila.server.enable_nbextensions=True
